[[main]]
  name = "Blog"
  pageRef = "posts"
  weight = 10

[[main]]
  name = "Projects"
  pageRef = "projects"
  weight = 20

[[main]]
  name = "Equipment"
  pageRef = "equipment"
  weight = 30

[[main]]
  name = "Tags"
  pageRef = "tags"
  weight = 40

# Footer menu
[[footer]]
  name = "Privacy"
  pageRef = "privacy"
  weight = 10

[[footer]]
  name = "License"
  url = "/LICENSE"
  weight = 20
